version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - mysql
    env_file:
      - .env
    command: sh -c "composer install"
    networks:
      - custom_network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    networks:
      - custom_network

volumes:
  mysql_data:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16